---
version: '2.4'
#only add core AM services here. Side services should be added to others.yml

services:

  am-org-role-mapping-service:
    image: "hmctspublic.azurecr.io/am/org-role-mapping-service:pr-57"
    container_name: am-org-role-mapping-service
    environment:
      AM_ROLE_ASSIGNMENT_SERVICE_SECRET: AAAAAAAAAAAAAAAA
      LD_SDK_KEY: "${LD_SDK_KEY}"
      ROLE_ASSIGNMENT_S2S_AUTHORISED_SERVICES: ccd_gw,am_role_assignment_service, am_org_role_mapping_service
      IDAM_USER_URL: http://idam-api:5000
      IDAM_S2S_URL: http://service-auth-provider-api:8080
      OPEN_ID_API_BASE_URI: http://idam-api:5000/o
      OIDC_ISSUER_URL: http://idam-api:8080/openam/oauth2/hmcts
      AZURE_APPLICATIONINSIGHTS_INSTRUMENTATIONKEY:
      REFORM_SERVICE_NAME: am-org-role-mapping-service
      AMQP_HOST: rd-servicebus-sandbox.servicebus.windows.net
      AMQP_SHARED_ACCESS_KEY_NAME: "${AMQP_SHARED_ACCESS_KEY_NAME}"
      AMQP_SHARED_ACCESS_KEY_VALUE: "${AMQP_SHARED_ACCESS_KEY_VALUE}"
      AMQP_TOPIC_NAME: rd-caseworker-topic-sandbox/subscriptions/temporary
      ORG_ROLE_MAPPING_IDAM_ADMIN_USERID: TEST_AM_USER4_BEFTA@test.local
      ROLE_ASSIGNMENT_APP_URL: http://am-role-assignment-service:4096
      CASE_WORKER_REF_APP_URL: http://rd-caseworker-ref-api:8095
      REFORM_TEAM: am
      REFORM_ENVIRONMENT: local
      # Uncomment this line to enable JVM debugging and uncomment the port mapping below
      #  JAVA_TOOL_OPTIONS: -XX:InitialRAMPercentage=30.0 -XX:MaxRAMPercentage=65.0 -XX:MinRAMPercentage=30.0 -XX:+UseConcMarkSweepGC -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005
    ports:
      - 4098:4098
      # Uncomment this and the JAVA_TOOL_OPTIONS flag for JVM debugging
      #- 5005:5005
    depends_on:
      idam-api:
        condition: service_started
      am-role-assignment-service:
        condition: service_started
      am-shared-database:
        condition: service_started
    networks:
      - am-network


  am-role-assignment-service:
    image: "hmctspublic.azurecr.io/am/role-assignment-service:latest"
    container_name: am-role-assignment-service
    environment:
        ROLE_ASSIGNMENT_DB_HOST: am-shared-database
        ROLE_ASSIGNMENT_DB_NAME: role_assignment
        ROLE_ASSIGNMENT_DB_PORT: 5432
        ROLE_ASSIGNMENT_DB_USERNAME: am
        ROLE_ASSIGNMENT_DB_PASSWORD: am
        ROLE_ASSIGNMENT_DB_OPTIONS: ?stringtype=unspecified
        AM_ROLE_ASSIGNMENT_SERVICE_SECRET: AAAAAAAAAAAAAAAA
        LD_SDK_KEY: "${LD_SDK_KEY}"
        ROLE_ASSIGNMENT_S2S_AUTHORISED_SERVICES: ccd_gw,am_role_assignment_service,am_org_role_mapping_service
        IDAM_USER_URL: http://idam-api:5000
        IDAM_S2S_URL: http://service-auth-provider-api:8080
        OPEN_ID_API_BASE_URI: http://idam-api:5000/o
        OIDC_ISSUER_URL: http://idam-api:8080/openam/oauth2/hmcts
        IDAM_CLIENT_ID: am_docker
        IDAM_CLIENT_SECRET: am_docker_secret
        IDAM_ADMIN_USERID: ras.admin@hmcts.net
        IDAM_ADMIN_PASSWORD: Pa55word11
        IDAM_ADMIN_SCOPE: search-user
        CCD_DATA_STORE_URL: http://ccd-data-store-api:4452
        AZURE_APPLICATIONINSIGHTS_INSTRUMENTATIONKEY:
        REFORM_SERVICE_NAME: am-role-assignment-service
        REFORM_TEAM: am
        REFORM_ENVIRONMENT: local
      # Uncomment this line to enable JVM debugging and uncomment the port mapping below
      #  JAVA_TOOL_OPTIONS: -XX:InitialRAMPercentage=30.0 -XX:MaxRAMPercentage=65.0 -XX:MinRAMPercentage=30.0 -XX:+UseConcMarkSweepGC -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005
    ports:
      - 4096:4096
      # Uncomment this and the JAVA_TOOL_OPTIONS flag for JVM debugging
      #- 5005:5005
    depends_on:
      idam-api:
        condition: service_started
      am-shared-database:
        condition: service_started
    networks:
      - am-network

  service-auth-provider-api:
    image: "hmctspublic.azurecr.io/rpe/service-auth-provider:latest"
    healthcheck:
      interval: 10s
      timeout: 10s
      retries: 10
    ports:
      - 4502:8080
    environment:
      SERVER_PORT: 8080
      JWT_KEY: wThK0f0/lh3FlxFcL4xUWDMI5C1J9KyQBgXV4wseh1e5J1uYJIjvTvArHxQDrYoHJ23xFxjHkOnvNbR5dXRoxA==
      MICROSERVICEKEYS_AM_ROLE_ASSIGNMENT_SERVICE: "AAAAAAAAAAAAAAAA"
      MICROSERVICEKEYS_AM_ORG_ROLE_MAPPING_SERVICE: "AAAAAAAAAAAAAAAA"
      MICROSERVICEKEYS_CCD_DATA: "${IDAM_KEY_CCD_DATA_STORE}"
      MICROSERVICEKEYS_CCD_GW: "${IDAM_KEY_CCD_GATEWAY}"
      MICROSERVICEKEYS_CCD_DEFINITION: "${IDAM_KEY_CCD_DEFINITION_STORE}"
      MICROSERVICEKEYS_RD_CASEWORKER_REF_API: "AAAAAAAAAAAAAAAA"
      MICROSERVICEKEYS_RD_USER_PROFILE_API: "AAAAAAAAAAAAAAAA"
      TESTING_SUPPORT_ENABLED: "true"
    networks:
      - am-network

  am-shared-database:
    build: ../database
    healthcheck:
      interval: 10s
      timeout: 10s
      retries: 10
    environment:
      - ROLE_ASSIGNMENT_DB_USERNAME=am
      - ROLE_ASSIGNMENT_DB_PASSWORD=am
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5451:5432
#    volumes:
#      - am-docker-am-shared-database-data:/var/lib/postgresql/data
    networks:
      - am-network

volumes:
  am-docker-am-shared-database-data:
  wiremock:

networks:
  am-network:
    external: true
