---
version: '2.4'
#only add required RD services here.

services:

  rd-caseworker-ref-api:
    image: "hmctspublic.azurecr.io/rd/caseworker-ref-api:latest"
    container_name: rd-caseworker-ref-api
    environment:
        POSTGRES_HOST: am-shared-database
        POSTGRES_PORT: 5432
        POSTGRES_DB_NAME: dbrdcaseworker
        POSTGRES_USERNAME: am
        POSTGRES_PASSWORD: am
        S2S_SECRET: AAAAAAAAAAAAAAAA
        CRD_S2S_AUTHORISED_SERVICES: rd_caseworker_ref_api,rd_professional_api,am_org_role_mapping_service
        idam_url: http://idam-api:5000
        S2S_URL: http://service-auth-provider-api:8080
        IDAM_CLIENT_ID: am_docker
        USER_PROFILE_URL: http://rd-user-profile-api:8091
        OPEN_ID_API_BASE_URI: http://idam-api:5000/o
        OIDC_ISSUER_URL: http://idam-api:8080/openam/oauth2/hmcts
        RD_LD_SDK_KEY: "${RD_LD_SDK_KEY}"
        LAUNCH_DARKLY_ENV: preview
        CWRD_MQ_HOST: rd-servicebus-sandbox.servicebus.windows.net
        CWRD_MQ_USERNAME: SendAndListenSharedAccessKey
        CWRD_MQ_PASSWORD: "${AMQP_SHARED_ACCESS_KEY_VALUE}"
        CWRD_MQ_TOPIC_NAME: rd-caseworker-topic-sandbox
        AZURE_APPLICATIONINSIGHTS_INSTRUMENTATIONKEY:
        REFORM_SERVICE_NAME: rd-caseworker-ref-api
        REFORM_TEAM: rd
        REFORM_ENVIRONMENT: local
      # Uncomment this line to enable JVM debugging and uncomment the port mapping below
      #  JAVA_TOOL_OPTIONS: -XX:InitialRAMPercentage=30.0 -XX:MaxRAMPercentage=65.0 -XX:MinRAMPercentage=30.0 -XX:+UseConcMarkSweepGC -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005
    ports:
      - 8095:8095
      # Uncomment this and the JAVA_TOOL_OPTIONS flag for JVM debugging
      #- 5005:5005
    depends_on:
      am-shared-database:
        condition: service_started
      rd-user-profile-api:
        condition: service_started
    networks:
      - am-network

  rd-user-profile-api:
    image: "hmctspublic.azurecr.io/rd/user-profile-api:pr-607"
    container_name: rd-user-profile-api
    environment:
      POSTGRES_HOST: am-shared-database
      POSTGRES_PORT: 5432
      POSTGRES_DB_NAME: dbuserprofile
      POSTGRES_USERNAME: am
      POSTGRES_PASSWORD: am
      S2S_SECRET: AAAAAAAAAAAAAAAA
      PRD_S2S_AUTHORISED_SERVICES: rd_professional_api,rd_user_profile_api,xui_webapp,finrem_payment_service,fpl_case_service,iac,aac_manage_case_assignment,divorce_frontend,rd_caseworker_ref_api,am_org_role_mapping_service
      idam_url: http://idam-api:5000
      S2S_URL: http://service-auth-provider-api:8080
      IDAM_CLIENT_ID: am_docker
      OPEN_ID_API_BASE_URI: http://idam-api:5000/o
      OIDC_ISSUER_URL: http://idam-api:8080/openam/oauth2/hmcts
      AZURE_APPLICATIONINSIGHTS_INSTRUMENTATIONKEY:
      REFORM_SERVICE_NAME: rd-user-profile-api
      REFORM_TEAM: rd
      REFORM_ENVIRONMENT: local
      # Uncomment this line to enable JVM debugging and uncomment the port mapping below
      #  JAVA_TOOL_OPTIONS: -XX:InitialRAMPercentage=30.0 -XX:MaxRAMPercentage=65.0 -XX:MinRAMPercentage=30.0 -XX:+UseConcMarkSweepGC -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005
    ports:
      - 8091:8091
      # Uncomment this and the JAVA_TOOL_OPTIONS flag for JVM debugging
      #- 5005:5005
    depends_on:
      am-shared-database:
        condition: service_started
      idam-api:
        condition: service_started
    networks:
      - am-network

networks:
  am-network:
    external: true
